source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "sidekiq", "~> 7.0"
gem "sidekiq-cron", "~> 1.12"
gem "connection_pool", "~> 2.4"
gem "dotenv-rails"
gem "httparty"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "sprockets-rails", "~> 3.5"
gem "blazer", "~> 3.4"
gem "thruster", "~> 0.1.22"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
